### ISSUE TITLE
Error message: "SystemExit: QUIT: You must pass a country list on CSV format."

### ISSUE THREAD

**Issue by sophia-the-dev** [Lewuathe/COVID19-SIR#31]
Sorry in advance: I'm a beginner in Python so I know this error sounds simple to fix but I am so lost!

Thank you!

**Comment by sunprinceS** [comment]
You should pass the countries you want to observe in `--countries` args (separated by ',').
For example,
`python3 solver.py --countries "United Kingdom,Japan,Taiwan*"`
